# Generated by Django 5.2.4 on 2025-07-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_folder_parent_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
    ]
